"""auto update

Revision ID: 786a19116401
Revises: 9eac954f8bef
Create Date: 2026-01-21 17:58:46.316785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786a19116401'
down_revision: Union[str, Sequence[str], None] = '9eac954f8bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('account_status', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('consecutive_months_paid', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('months_late', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'membership_class',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('profiles', 'paid_months_count')
    op.drop_column('profiles', 'join_fee_paid')
    op.drop_column('profiles', 'join_fee_paid_at')
    op.drop_column('profiles', 'membership_status')
    op.drop_column('profiles', 'is_eligible')
    op.drop_column('profiles', 'cpf')
    op.drop_column('profiles', 'months_in_arrears')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('months_in_arrears', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('is_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('membership_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('join_fee_paid_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('join_fee_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('paid_months_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'membership_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'stripe_subscription_id')
    op.drop_column('profiles', 'months_late')
    op.drop_column('profiles', 'consecutive_months_paid')
    op.drop_column('profiles', 'account_status')
    # ### end Alembic commands ###