"""auto update

Revision ID: de6bd0ee0370
Revises: 786a19116401
Create Date: 2026-01-21 18:06:05.155710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6bd0ee0370'
down_revision: Union[str, Sequence[str], None] = '786a19116401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('fund_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_collected', sa.Float(), nullable=False),
    sa.Column('total_disbursed', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('active_members', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_statistics_id'), 'fund_statistics', ['id'], unique=False)
    op.create_table('success_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_name', sa.String(), nullable=False),
    sa.Column('story', sa.String(), nullable=False),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_success_stories_id'), 'success_stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_success_stories_id'), table_name='success_stories')
    op.drop_table('success_stories')
    op.drop_index(op.f('ix_fund_statistics_id'), table_name='fund_statistics')
    op.drop_table('fund_statistics')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###